# Generated by Django 2.1.3 on 2019-03-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='service_data',
        ),
    ]
