# Generated by Django 2.1.7 on 2019-03-31 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0002_auto_20190330_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='studentmessage',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='volunteermessage',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单创建时间'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='服务日期'),
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation_service.Reservation', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='source',
            field=models.CharField(blank=True, max_length=16, verbose_name='消息来源'),
        ),
        migrations.AddField(
            model_name='volunteermessage',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation_service.Reservation', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='volunteermessage',
            name='source',
            field=models.CharField(blank=True, max_length=16, verbose_name='消息来源'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_finished',
            field=models.BooleanField(default=False, verbose_name='学生确认完成'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_read',
            field=models.BooleanField(default=False, verbose_name='学生是否已读'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='volunteer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='information_service.Volunteer', verbose_name='志愿者'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='volunteer_finished',
            field=models.BooleanField(default=False, verbose_name='志愿者确认完成'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='volunteer_read',
            field=models.BooleanField(default=False, verbose_name='志愿者是否已读'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='reservation_state',
            field=models.IntegerField(default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='volunteermessage',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='volunteermessage',
            name='reservation_state',
            field=models.IntegerField(default=1, verbose_name='订单状态'),
        ),
    ]
