# Generated by Django 2.1.3 on 2019-03-30 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0002_auto_20190330_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次更新时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='服务日期'),
        ),
    ]
