# Generated by Django 2.1.3 on 2019-03-31 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0003_auto_20190330_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='volunteer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='information_service.Volunteer', verbose_name='志愿者'),
        ),
    ]
