# Generated by Django 2.1.7 on 2019-03-31 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0003_auto_20190331_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='information_service.Volunteer', verbose_name='志愿者'),
        ),
    ]
