# Generated by Django 2.1.3 on 2019-03-31 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0004_auto_20190331_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='volunteer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='information_service.Volunteer', verbose_name='志愿者'),
        ),
    ]
