# Generated by Django 2.1.3 on 2019-04-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0007_auto_20190331_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation_service.Reservation', verbose_name='订单'),
        ),
    ]
