# Generated by Django 2.1.3 on 2019-04-06 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='轨迹时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_service.Student', verbose_name='学生')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_service.Volunteer', verbose_name='志愿者')),
            ],
        ),
    ]
