# Generated by Django 2.1.7 on 2019-03-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edu_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=32)),
                ('student_name', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.BooleanField()),
                ('name', models.CharField(max_length=32)),
                ('image', models.FilePathField()),
                ('phone_number', models.CharField(max_length=12)),
                ('wechat', models.CharField(max_length=32)),
                ('edu_historys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_service.Edu_history')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vaild', models.BooleanField()),
                ('school', models.CharField(max_length=32)),
                ('class_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.BooleanField()),
                ('image', models.FilePathField()),
                ('title', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=12)),
                ('wechat', models.CharField(max_length=32)),
                ('edu_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_service.Edu_comment')),
                ('edu_historys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_service.Edu_history')),
                ('edu_subjects', models.ManyToManyField(to='information_service.Subject')),
            ],
        ),
    ]
