# Generated by Django 2.1.3 on 2019-03-22 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 9, 49, 15, 934115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 9, 49, 15, 934078, tzinfo=utc)),
        ),
    ]
