# Generated by Django 2.1.3 on 2019-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(default='http://47.105.150.105:8000/media/images/Student/student.jpg', max_length=128, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='certification',
            field=models.CharField(default='http://47.105.150.105:8000/media/images/Student/student.jpg', max_length=128, verbose_name='学生证照片'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.CharField(default='http://47.105.150.105:8000/media/images/Volunteer/volunteer.png', max_length=128, verbose_name='头像'),
        ),
    ]
