# Generated by Django 2.1.7 on 2019-03-30 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='volunteerfeedback',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
