# Generated by Django 2.1.3 on 2019-03-23 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0002_auto_20190322_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 4, 29, 7, 64043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 4, 29, 7, 64009, tzinfo=utc)),
        ),
    ]
