# Generated by Django 2.1.7 on 2019-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0002_auto_20190330_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, max_length=8, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, max_length=8, verbose_name='学科类型'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='学科名'),
        ),
    ]
