# Generated by Django 2.1.3 on 2019-04-10 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0002_auto_20190408_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 22, 18, 41, 830599), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 22, 18, 41, 828341), verbose_name='创建时间'),
        ),
    ]
