# Generated by Django 2.1.3 on 2019-04-10 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_service', '0004_auto_20190410_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 22, 21, 33, 493611), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 22, 21, 33, 489846), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='荣誉称号'),
        ),
    ]
